# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_connection_setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connection_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 401, 301))
        self.widget.setStyleSheet("background-color: hsl(0,0,50);color: hsl(0,0,255)")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(50, 80, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cb_con_setup_port = QtWidgets.QComboBox(self.widget)
        self.cb_con_setup_port.setGeometry(QtCore.QRect(140, 70, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_con_setup_port.setFont(font)
        self.cb_con_setup_port.setStyleSheet("background-color: hsl(0,0,255);color: hsl(0,0,0)")
        self.cb_con_setup_port.setObjectName("cb_con_setup_port")
        self.cb_con_setup_baud = QtWidgets.QComboBox(self.widget)
        self.cb_con_setup_baud.setGeometry(QtCore.QRect(140, 130, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_con_setup_baud.setFont(font)
        self.cb_con_setup_baud.setStyleSheet("background-color: hsl(0,0,255);color: hsl(0,0,0)")
        self.cb_con_setup_baud.setObjectName("cb_con_setup_baud")
        self.but_con_setup_ok = QtWidgets.QPushButton(self.widget)
        self.but_con_setup_ok.setGeometry(QtCore.QRect(40, 240, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_con_setup_ok.setFont(font)
        self.but_con_setup_ok.setStyleSheet("background-color: hsl(0,0,255);color: hsl(0,0,0)")
        self.but_con_setup_ok.setObjectName("but_con_setup_ok")
        self.but_con_setup_refresh = QtWidgets.QPushButton(self.widget)
        self.but_con_setup_refresh.setGeometry(QtCore.QRect(150, 240, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_con_setup_refresh.setFont(font)
        self.but_con_setup_refresh.setStyleSheet("background-color: hsl(0,0,255);color: hsl(0,0,0)")
        self.but_con_setup_refresh.setObjectName("but_con_setup_refresh")
        self.but_con_setup_cancel = QtWidgets.QPushButton(self.widget)
        self.but_con_setup_cancel.setGeometry(QtCore.QRect(260, 240, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_con_setup_cancel.setFont(font)
        self.but_con_setup_cancel.setStyleSheet("background-color: hsl(0,0,255);color: hsl(0,0,0)")
        self.but_con_setup_cancel.setObjectName("but_con_setup_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "PORT"))
        self.label_2.setText(_translate("Dialog", "BAUD RATE"))
        self.but_con_setup_ok.setText(_translate("Dialog", "OK"))
        self.but_con_setup_refresh.setText(_translate("Dialog", "Refresh"))
        self.but_con_setup_cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Connection_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
